# Generated by Django 5.0 on 2023-12-11 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_produk_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='kategori',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.kategori'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='status',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.status'),
        ),
    ]
